"""initial models

Revision ID: 29ac9a35b341
Revises: 
Create Date: 2026-05-23 02:20:47.833804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '29ac9a35b341'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('max_influencers', sa.Integer(), nullable=False),
    sa.Column('max_analyses_per_month', sa.Integer(), nullable=False),
    sa.Column('allow_benchmarking', sa.Boolean(), nullable=False),
    sa.Column('price_brl_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agencies_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agencies_plan_id'), ['plan_id'], unique=False)

    op.create_table('api_usage_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usage_logs_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_logs_called_at'), ['called_at'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('brand_name', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('budget_brl_cents', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ENDED', 'CANCELLED', name='campaign_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_brand_name'), ['brand_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_period_end'), ['period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_period_start'), ['period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('influencers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('niche', sa.String(length=80), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ARCHIVED', name='influencer_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('influencers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_influencers_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_influencers_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_influencers_niche'), ['niche'], unique=False)
        batch_op.create_index(batch_op.f('ix_influencers_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('oauth_provider', sa.Enum('GOOGLE', 'MICROSOFT', name='oauth_provider'), nullable=False),
    sa.Column('oauth_id', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_provider', 'oauth_id', name='uq_users_oauth_identity')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('campaign_influencers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('influencer_id', sa.Uuid(), nullable=False),
    sa.Column('fee_brl_cents', sa.BigInteger(), nullable=False),
    sa.Column('deliverables', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'influencer_id', name='uq_campaign_influencer_pair')
    )
    with op.batch_alter_table('campaign_influencers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_influencers_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_influencers_influencer_id'), ['influencer_id'], unique=False)

    op.create_table('oauth_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.Enum('GOOGLE', 'MICROSOFT', name='oauth_provider'), nullable=False),
    sa.Column('state_token', sa.String(length=128), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_states_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_states_state_token'), ['state_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_oauth_states_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('generated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('format', sa.Enum('PDF', 'JSON', name='report_format'), nullable=False),
    sa.Column('sections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_generated_by_user_id'), ['generated_by_user_id'], unique=False)

    op.create_table('social_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('influencer_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'TIKTOK', 'YOUTUBE', name='platform'), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=False),
    sa.Column('platform_user_id', sa.String(length=120), nullable=True),
    sa.Column('follower_count', sa.BigInteger(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('influencer_id', 'platform', 'handle', name='uq_social_accounts_identity')
    )
    with op.batch_alter_table('social_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_accounts_influencer_id'), ['influencer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_accounts_platform'), ['platform'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('social_account_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('platform_post_id', sa.String(length=160), nullable=False),
    sa.Column('post_type', sa.Enum('IMAGE', 'VIDEO', 'REEL', 'STORY', 'SHORT', 'CAROUSEL', name='post_type'), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=1000), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('reach_total', sa.BigInteger(), nullable=False),
    sa.Column('reach_organic', sa.BigInteger(), nullable=False),
    sa.Column('reach_paid', sa.BigInteger(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('likes', sa.BigInteger(), nullable=False),
    sa.Column('comments_count', sa.BigInteger(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('saves', sa.BigInteger(), nullable=False),
    sa.Column('avg_watch_time', sa.Float(), nullable=True),
    sa.Column('retention_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_account_id', 'platform_post_id', name='uq_posts_platform_identity')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_social_account_id'), ['social_account_id'], unique=False)

    op.create_table('ai_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='sentiment_label'), nullable=False),
    sa.Column('script_score', sa.Float(), nullable=True),
    sa.Column('brand_coherence_score', sa.Float(), nullable=True),
    sa.Column('bot_probability', sa.Float(), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('key_phrases', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('recommendations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('sentiment_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw_response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analyses_analyzed_at'), ['analyzed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_post_id'), ['post_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('platform_comment_id', sa.String(length=160), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_handle', sa.String(length=120), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'platform_comment_id', name='uq_comments_platform_identity')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_post_id'))

    op.drop_table('comments')
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analyses_post_id'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_analyzed_at'))

    op.drop_table('ai_analyses')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_social_account_id'))
        batch_op.drop_index(batch_op.f('ix_posts_posted_at'))
        batch_op.drop_index(batch_op.f('ix_posts_campaign_id'))

    op.drop_table('posts')
    with op.batch_alter_table('social_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_accounts_platform'))
        batch_op.drop_index(batch_op.f('ix_social_accounts_influencer_id'))

    op.drop_table('social_accounts')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_generated_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_reports_agency_id'))

    op.drop_table('reports')
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_states_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_states_state_token'))
        batch_op.drop_index(batch_op.f('ix_oauth_states_expires_at'))

    op.drop_table('oauth_states')
    with op.batch_alter_table('campaign_influencers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_influencers_influencer_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_influencers_campaign_id'))

    op.drop_table('campaign_influencers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_agency_id'))

    op.drop_table('users')
    with op.batch_alter_table('influencers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_influencers_status'))
        batch_op.drop_index(batch_op.f('ix_influencers_niche'))
        batch_op.drop_index(batch_op.f('ix_influencers_display_name'))
        batch_op.drop_index(batch_op.f('ix_influencers_agency_id'))

    op.drop_table('influencers')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_period_start'))
        batch_op.drop_index(batch_op.f('ix_campaigns_period_end'))
        batch_op.drop_index(batch_op.f('ix_campaigns_brand_name'))
        batch_op.drop_index(batch_op.f('ix_campaigns_agency_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('api_usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_logs_called_at'))
        batch_op.drop_index(batch_op.f('ix_api_usage_logs_agency_id'))

    op.drop_table('api_usage_logs')
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agencies_plan_id'))
        batch_op.drop_index(batch_op.f('ix_agencies_name'))

    op.drop_table('agencies')
    op.drop_table('plans')
    # ### end Alembic commands ###
