"""add needs_analysis to posts

Revision ID: 6598a89ce9fa
Revises: 29ac9a35b341
Create Date: 2026-06-05 16:19:13.178653

"""
from alembic import op
import sqlalchemy as sa


revision = '6598a89ce9fa'
down_revision = '29ac9a35b341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_analysis', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.create_index(batch_op.f('ix_posts_needs_analysis'), ['needs_analysis'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_needs_analysis'))
        batch_op.drop_column('needs_analysis')

    # ### end Alembic commands ###
